# Generated by Django 2.1.3 on 2019-10-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mzc', '0004_auto_20191001_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'OTHERS')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
